### ISSUE TITLE
Fichier md non converti en html

### ISSUE THREAD

**Issue by mahendra-mariadassou** [StateOfTheR/finistR2023#38]
Le fichier md de @HGangloff n'est ni converti en html ni inclus dans le site web. La site indexe la page:
https://stateofther.github.io/finistR2023/jit-example-pln.md 
qui renvoie une erreur 404. Il ne s'agit à priori pas d'un problème de format de yaml dans _quarto.yaml (cf #33), quarto permettant en théorie d'inclure des qmd et des md.

**Comment by HGangloff** [comment]
La page https://stateofther.github.io/finistR2023/jit-example-pln.html existe cependant, la conversion en html doit avoir lieu quand même... :roll_eyes:

**Comment by HGangloff** [comment]
Je vois pas trop. Sinon je convertis mes .md en .qmd avec des blocs de code non-executables

**Comment by HGangloff** [comment]
@mahendra-mariadassou 
En renommant simplement le .md en .qmd j'obtiens un .qmd statique, avec les cellules de sortie conservées. Je peux ainsi ajouter les .qmd dans _quarto.yml et ça devrait bien aller...

Maintenant le problème est que le site ne se construit plus à cause de julia :upside_down_face:

**Comment by MarieEtienne** [comment]
J'essaie de régler le problème Julia ce matin !
