### ISSUE TITLE
Problème pour faire un qmd Julia statique

### ISSUE THREAD

**Issue by Jo-Theo** [StateOfTheR/finistR2023#56]
Il est difficile de réaliser un conteneur qui contient Julia, pour le moment mes conteneurs sont super lourd (18GB) et ne tiens donc pas dans la mémoire d'un runner github... Je n'ai pas réussi à l'alléger et je ne peux rajouter de self-hosted runner sur ce projet. Pour le moment la seule possibilité est donc d'inclure le "R-Julia-Geostats.qmd" en statique.

Le fichier  "R-Julia-Geostats.qmd" est complexe à lancer, j'ai des erreurs. Les fichier 'meuse.txt' et 'meuse.grid.txt' semblent venir de la fonction data de R. Mais il faut les enregistrer en csv dans le dossier pour qu'ils puissent être lu par Julia. 
De plus la fonction CSV.File() ligne 402 n'est pas reconnue quand je le lance en local. 

Il n'y a pas d'auteur sur le fichier, mais dès que j'ai une version qui tourne en local je peux la rajouter sur le site !

**Comment by MarieEtienne** [comment]
Merci Theo de t'être acharné sur le sujet. Je pense que c'est Corentin qui avait géré ce fichier. Ta solution me convient très bien,. Est ce que tu peux mettre dans le fichier un petit warning qui explique ce que tu viens de dire et pourquoi ce R-Julia-Geostats.qmd est en statique contrairement aux autre s?
Merci encore

**Comment by julieaubert** [comment]
Et oui merci merci beaucoup Théodore. Pour qu'on se rappelle de tous ces petits problèmes : il a écrit un .qmd 
[ https://stateofther.github.io/finistR2023/how_to_maintain_a_dockerfile.html | https://stateofther.github.io/finistR2023/how_to_maintain_a_dockerfile.html ] 




De: "Marie Etienne" ***@***.***> 
À: "StateOfTheR/finistR2023" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Jeudi 14 Septembre 2023 10:16:55 
Objet: Re: [StateOfTheR/finistR2023] Problème pour faire un qmd Julia statique (Issue #56) 





Merci Theo de t'être acharné sur le sujet. Je pense que c'est Corentin qui avait géré ce fichier. Ta solution me convient très bien,. Est ce que tu peux mettre dans le fichier un petit warning qui explique ce que tu viens de dire et pourquoi ce R-Julia-Geostats.qmd est en statique contrairement aux autre s? 
Merci encore

**Comment by Jo-Theo** [comment]
Bonjour, 

Normalement le R julia va être déployable avec la dernière pull request : 
Reste à attendre. Pour le moment j'ai commenter les lignes qui font appel à la `focntion CairoMakie.plot()` que je n'ai pas réussie à la lancer en local.  J'ai réédité [la page sur la résolution](https://stateofther.github.io/finistR2023/how_to_maintain_a_dockerfile.html) avec mes changement d'ailleur le titre est pas forcément hyper indicatif... 

Pour finir dans les github action j'efface deux qmd, ce sont ces fichier qui m'on aidés à générer la version fixe. Donc il ne faut pas qu'il sois compilés avec le site car il vont encore tout casser avec leur Julia. Mais je préférai qu'ils soient disponibles sur le repository...

**Comment by Jo-Theo** [comment]
push worked
